# Generated by Django 3.2 on 2023-01-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_auto_20230124_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='start',
            field=models.DateField(auto_now=True),
        ),
    ]
